apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: dev
type: Opaque
data:
  ROOT_PASSWORD: <ENCODED>
  USER_PASSWORD: <ENCODED>


#generic secret creation(if you dont want to use secret.yml)
#kubectl create secret mysql-secrets --from-literal=ROOT_PASSWORD='***' --from-literal=USER_PASSWORD='***'